[package]
name = "sparconvert"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sparconvert"
path = "src/main.rs"

[dependencies]
spargebra = { version = "0.3.5", features = ["rdf-star"] }
uuid = { version = "1.16.0", features = ["v4"] }
serde_json = "1.0"
